---
- name: Copy config to home directory
  become: yes
  copy:
    src: /vagrant/admin.conf
    dest: /home/vagrant/admin.conf
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Update Environment
  become: yes
  lineinfile:
    path: /home/vagrant/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/home/vagrant/admin.conf'
    state: present

- name: Join Kubernetes Cluster
  become: yes
  command: "kubeadm join --discovery-token-unsafe-skip-ca-verification --token 2f1a31.00f66dec74fd53f3 192.168.1.10:6443"
