{{- $fullname := include "kafka.fullname" . -}}
{{- $name := include "kafka.name" . -}}
{{- $chart := include "kafka.chart" . -}}
{{- $root := . }}
{{ range .Values.nodes }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $fullname }}-k8s{{ . }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $root.Release.Name }}
      node: k8s{{ . }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $root.Release.Name }}
        node: k8s{{ . }}
    spec:
      containers:
        - name: {{ $root.Chart.Name }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - name: broker
              containerPort: 9092
              protocol: TCP
            - name: metrics
              containerPort: 7070
              protocol: TCP
            - name: broker-external
              containerPort: {{ add $root.Values.service.firstExternalBrokerPort . }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - mountPath: /var/tmp/data
              subPath: data
              name: kafka-data
            - mountPath: "/etc/kafka_jaas.conf"
              subPath: jaasconfig
              name: kafka-jaas-config
              readOnly: true
          command:
            - sh
            - -exc
            - |
              unset KAFKA_PORT && \
              exec /etc/confluent/docker/run
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_BROKER_ID
              value: "{{ . }}"
            - name: KAFKA_HEAP_OPTS
              value: "{{ $root.Values.environment.jvmFlags }}"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ $root.Values.zookeeper.name }}:{{ $root.Values.zookeeper.port }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ $fullname }}-k8s{{.}}:9092,EXTERNAL://k8s{{ . }}:{{ add $root.Values.service.firstExternalBrokerPort . }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:PLAINTEXT"
            - name: KAFKA_NUM_PARTITIONS
              value: "10"
            - name: KAFKA_DELETE_TOPICS
              value: "true"
            - name: KAFKA_AUTO_CREATE_TOPICS
              value: "true"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "24"
            - name: KAFKA_TRANSACTION_MAX_TIMEOUT_MS
              value: "3600000"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_LOG_DIRS
              value: "/var/tmp/data/kafka-logs"
            - name: KAFKA_DATA_DIRS
              value: "/var/tmp/data/kafka-logs"
            # - name: KAFKA_ZOOKEEPER_SET_ACL
            #   value: "true"
            - name: CONFLUENT_SUPPORT_METRICS_ENABLE
              value: "false"
            - name: NEXTBREAKPOINT_JAAS_CONFIG
              value: "/etc/kafka_jaas.conf"
          resources:
{{ toYaml $root.Values.resources | indent 12 }}
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: {{ $fullname }}-pvc-k8s{{ . }}
        - name: kafka-jaas-config
          secret:
            secretName: {{ $fullname }}-jaas-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s{{ . }}
    {{ end }}
